### ISSUE TITLE
TypeError: API.get_uuid() missing 1 required positional argument: 'username'

### ISSUE THREAD

**Issue by Eddiekungen20** [summer/mojang#24]
I have inputted a username but this error still occurs. How can I fix this?

**Comment by summer** [comment]
Hello, do you have a code example? The code works for me.

It sounds like you might be forgetting to create an instance of the API before using it. 

```py
from mojang import API

# Create an instance of an API session first
api = API()

# Then obtain the uuid via the instance
uuid = api.get_uuid("Notch")

print(uuid)
```
