### ISSUE TITLE
json.decoder.JSONDecodeError when querying a uuid that isnt a player

### ISSUE THREAD

**Issue by OskarZyg** [summer/mojang#3]
When you query a profile:
```py
profile = MojangAPI.get_profile("20e21989-5521-49df-9750-a4ef8bd5441b")
```
, expected output is `None` if the profile doesn't exist or `UserProfile` if it does, however, if you put a valid UUID, but one  that isn't a player, the method throws `json.decoder.JSONDecodeError`
```py
profile = MojangAPI.get_profile("20e21989-5521-49df-9750-a4ef8bd5441a") # This will error out!
````

**Comment by summer** [comment]
Thank you, this has been fixed.
