### ISSUE TITLE
Getting Bearer Token 

### ISSUE THREAD

**Issue by Pumpk1nMan** [summer/mojang#32]
Is there a way to input login: (Email, Password)
and getting it to print the bearer token?

**Comment by summer** [comment]
Yes, I would actually recommend saving down the bearer token if you plan on logging in a lot. This way, the entire Microsoft authentication flow is skipped and you can use an authenticated session instantly whenever you want.

**Example:**
```py
from mojang import Client

client = Client("YOUR_MICROSOFT_EMAIL", "YOUR_PASSWORD")

print(client.bearer_token)
```

**Comment by Pumpk1nMan** [comment]
Thank you!
