### ISSUE TITLE
"get_drop_timestamp" always returns ValueError

### ISSUE THREAD

**Issue by ghost** [summer/mojang#5]
The get_drop_timestamp() function always returns a ValueError, as it attempts to convert the username to a UUID, however since drop timestamps only work on names that aren't currently set to any profile, this makes it impossible to work.

Example:
```
drop_timestamp = MojangAPI.get_drop_timestamp(mazurr)
print(drop_timestamp)
```
Returns:

`ValueError: Username is invalid. Failed to convert username to UUID`

**Comment by ghost** [comment]
Noticed this was an issue on Mojang's end (Timestamp doesn't work for certain profiles), would like to see a workaround if possible.

**Comment by summer** [comment]
Thank you for reporting this. This is definitely a problem on Mojang's end (see [WEB-3367](https://bugs.mojang.com/browse/WEB-3367)), so the feature has been removed for now. I'll see if there are any workarounds when I have some time.
