### ISSUE TITLE
problem with `get_name_history`

### ISSUE THREAD

**Issue by ojmaster** [summer/mojang#9]
```
   name_data_dict["name"] = data["name"]
TypeError: string indices must be integers
```
getting this error anytime i call the `MojangAPI.get_name_history(uuid)`

**Comment by summer** [comment]
This endpoint has been deprecated as of last month, so it has been removed from the API. See: https://help.minecraft.net/hc/en-us/articles/8969841895693-Username-History-API-Removal-FAQ-
